require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: disable

Gemspec/RequiredRubyVersion:
  Exclude:
    - 'temporal_tables.gemspec'

Rails/ApplicationRecord:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/ExampleWording:
  Enabled: false
RSpec/InstanceVariable:
  Exclude:
    - spec/basic_history_spec.rb
RSpec/MultipleDescribes:
  Exclude:
    - spec/basic_history_spec.rb
RSpec/MultipleExpectations:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false 
Style/Documentation:
  Enabled: false
Style/HashSyntax:
  EnforcedShorthandSyntax: never 
Style/SymbolArray:
  Enabled: false
